package uk.gov.hmrc.agentinvitationsfrontend.support

import uk.gov.hmrc.agentinvitationsfrontend.models.CurrentAuthorisationRequest
import uk.gov.hmrc.agentinvitationsfrontend.services.CurrentAuthorisationRequestCache

class TestCurrentAuthorisationRequestCache extends CurrentAuthorisationRequestCache with TestCache[CurrentAuthorisationRequest]
